CREATE TABLE fCota_Parlamentar (codlegislatura int, 
datemissao datetime, 
idedocumento int, 
idecadastro int, 
nucarteiraparlamentar int, 
nudeputadoid int,
ano int,
nummes int,
numsubcota int,
partido varchar(200),
estado varchar(200),
parlamentares varchar(200),
txtdescricao varchar(200),
fornecedor varchar(200),
txtnumero varchar(200),
passsageiro varchar(200),
txttrecho varchar(200),
vlrdocumento decimal(8, 2),
vlrliquido decimal(8, 2));